CANDIDATE = {
    "name": "Yernar Ibadulla",
    "location": "Астана",
    "employment": "full_time",
    "work_formats": [
        "remote",
        "hybrid",
        "office",
    ],
    "minimum_salary": 250_000,
    "skills": {
        "Python",
        "JavaScript",
        "React",
        "Node.js",
        "SQL",
        "REST API",
        "AI",
        "LLM",
        "n8n",
        "Make",
        "Git",
        "Linux",
        "ETL",
        "BI",
        "Power BI",
        "HTML",
        "CSS",
    },
    "languages": {
        "Русский": "C2",
        "Казахский": "C2",
        "Английский": "B2+",
    },
    "desired_roles": {
        "Python Developer",
        "Backend Developer",
        "Automation Developer",
        "AI Developer",
        "AI Integration Developer",
        "BI Developer",
        "ETL Developer",
        "Support Engineer",
        "QA Engineer",
    },
}